# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisMainGUI(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(370, 10, 601, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\BSc CSD Sem 6\Project\JarvisGUI\JarvisImages\logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.listeningImg = QtWidgets.QLabel(Dialog)
        self.listeningImg.setEnabled(False)
        self.listeningImg.setGeometry(QtCore.QRect(10, 100, 361, 261))
        self.listeningImg.setText("")
        self.listeningImg.setPixmap(QtGui.QPixmap("D:\BSc CSD Sem 6\Project\JarvisGUI\JarvisImages\\voicerecog.gif"))
        self.listeningImg.setScaledContents(True)
        self.listeningImg.setObjectName("listeningImg")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(1020, 100, 261, 481))
        self.label_3.setStyleSheet("background-color:transparent;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\BSc CSD Sem 6\Project\JarvisGUI\JarvisImages\ironman.webp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.arc_reactor = QtWidgets.QLabel(Dialog)
        self.arc_reactor.setGeometry(QtCore.QRect(390, 110, 511, 291))
        self.arc_reactor.setText("")
        self.arc_reactor.setPixmap(QtGui.QPixmap("D:\BSc CSD Sem 6\Project\JarvisGUI\JarvisImages\\arcreactor.gif"))
        self.arc_reactor.setScaledContents(True)
        self.arc_reactor.setObjectName("arc_reactor")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(380, 110, 111, 91))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\BSc CSD Sem 6\Project\JarvisGUI\JarvisImages\\blkimg.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(800, 310, 111, 91))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\BSc CSD Sem 6\Project\JarvisGUI\JarvisImages\\blkimg.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.micImg = QtWidgets.QLabel(Dialog)
        self.micImg.setGeometry(QtCore.QRect(10, 100, 361, 261))
        self.micImg.setText("")
        self.micImg.setPixmap(QtGui.QPixmap("D:\BSc CSD Sem 6\Project\JarvisGUI\JarvisImages\\listening.gif"))
        self.micImg.setScaledContents(True)
        self.micImg.setObjectName("micImg")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 420, 1041, 271))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "border-color: rgb(255, 255, 255);\n"
                                 "border-radius: 30px;\n"
                                 "border-width: 5px 5px 5px 5px;\n"
                                 "border-style: solid;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.submitBtn = QtWidgets.QPushButton(self.frame)
        self.submitBtn.setGeometry(QtCore.QRect(880, 200, 141, 51))
        self.submitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitBtn.setStyleSheet("border-image: url(D:/BSc CSD Sem 6/Project/JarvisGUI/JarvisImages/startButton.png);")
        self.submitBtn.setText("")
        self.submitBtn.setObjectName("submitBtn")
        self.terminalInputBox = QtWidgets.QLineEdit(self.frame)
        self.terminalInputBox.setGeometry(QtCore.QRect(20, 200, 841, 51))
        self.terminalInputBox.setStyleSheet("font: 15pt \"Segoe UI\";\n"
                                            "padding-left: 10px;")
        self.terminalInputBox.setObjectName("terminalInputBox")
        self.terminalOutputBox = QtWidgets.QPlainTextEdit(self.frame)
        self.terminalOutputBox.setGeometry(QtCore.QRect(20, 20, 1001, 161))
        self.terminalOutputBox.setObjectName("terminalOutputBox")
        self.terminalOutputBox.setStyleSheet("font: 12pt \"Segoe UI\";\n"
                                            "padding-left: 10px;")
        # Modify font style and size for terminalOutputBox
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(10)
        # self.terminalOutputBox.setFont(font)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(1110, 620, 131, 61))
        self.pushButton.setStyleSheet("border-image: url(D:/BSc CSD Sem 6/Project/JarvisGUI/JarvisImages/exitButton.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.terminalInputBox.setPlaceholderText(_translate("Dialog", "Enter your command"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_JarvisMainGUI()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
