# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 550)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.logo = QtWidgets.QLabel(Dialog)
        self.logo.setGeometry(QtCore.QRect(40, 10, 640, 80))
        self.logo.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("D:\BSc CSD Sem 6\Project\JarvisGUI\JarvisImages\logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.gif1 = QtWidgets.QLabel(Dialog)
        self.gif1.setGeometry(QtCore.QRect(-20, 110, 711, 341))
        self.gif1.setText("")
        self.gif1.setPixmap(QtGui.QPixmap("D:\BSc CSD Sem 6\Project\JarvisGUI\JarvisImages\samplegui3.gif"))
        self.gif1.setScaledContents(True)
        self.gif1.setObjectName("gif1")
        self.startBtn = QtWidgets.QPushButton(Dialog)
        self.startBtn.setGeometry(QtCore.QRect(30, 480, 141, 61))
        self.startBtn.setStyleSheet("border-image: url(D:/BSc CSD Sem 6/Project/JarvisGUI/JarvisImages/startButton.png);")
        self.startBtn.setText("")
        self.startBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startBtn.setObjectName("startBtn")
        self.loginBtn = QtWidgets.QPushButton(Dialog)
        self.loginBtn.setGeometry(QtCore.QRect(280, 480, 141, 61))
        self.loginBtn.setStyleSheet("border-image: url(D:/BSc CSD Sem 6/Project/JarvisGUI/JarvisImages/loginButton.png);")
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn.setText("")
        self.loginBtn.setObjectName("loginBtn")
        self.exitBtn = QtWidgets.QPushButton(Dialog)
        self.exitBtn.setGeometry(QtCore.QRect(520, 480, 141, 61))
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitBtn.setStyleSheet("border-image: url(D:/BSc CSD Sem 6/Project/JarvisGUI/JarvisImages/exitButton.png);")
        self.exitBtn.setText("")
        self.exitBtn.setObjectName("exitBtn")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
