# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1080, 720)
        Widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.logo = QtWidgets.QLabel(Widget)
        self.logo.setGeometry(QtCore.QRect(260, 0, 561, 81))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../JarvisImages/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.frame = QtWidgets.QFrame(Widget)
        self.frame.setGeometry(QtCore.QRect(210, 90, 681, 601))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 30px;\n"
"border-width: 5px 5px 5px 5px;\n"
"border-style: solid;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.retryBtn = QtWidgets.QPushButton(self.frame)
        self.retryBtn.setGeometry(QtCore.QRect(60, 490, 141, 61))
        self.retryBtn.setStyleSheet("border-image: url(:/JarvisImages/retryButton.png);")
        self.retryBtn.setText("")
        self.retryBtn.setObjectName("retryBtn")
        self.backBtn = QtWidgets.QPushButton(self.frame)
        self.backBtn.setGeometry(QtCore.QRect(270, 490, 141, 61))
        self.backBtn.setStyleSheet("border-image: url(:/JarvisImages/backButton.png);")
        self.backBtn.setText("")
        self.backBtn.setObjectName("backBtn")
        self.exitBtn = QtWidgets.QPushButton(self.frame)
        self.exitBtn.setGeometry(QtCore.QRect(490, 490, 141, 61))
        self.exitBtn.setStyleSheet("border-image: url(:/JarvisImages/exitButton.png);")
        self.exitBtn.setText("")
        self.exitBtn.setObjectName("exitBtn")
        self.userNameEntry = QtWidgets.QLineEdit(self.frame)
        self.userNameEntry.setGeometry(QtCore.QRect(112, 84, 481, 81))
        self.userNameEntry.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"padding-left: 10px;")
        self.userNameEntry.setObjectName("userNameEntry")
        self.passwordEntry = QtWidgets.QLineEdit(self.frame)
        self.passwordEntry.setGeometry(QtCore.QRect(110, 220, 481, 81))
        self.passwordEntry.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"padding-left: 10px;")
        self.passwordEntry.setObjectName("passwordEntry")
        self.loginBtn = QtWidgets.QPushButton(self.frame)
        self.loginBtn.setGeometry(QtCore.QRect(140, 390, 141, 61))
        self.loginBtn.setStyleSheet("border-image: url(:/JarvisImages/retryButton.png);\n"
"border-image: url(:/JarvisImages/loginButton.png);")
        self.loginBtn.setText("")
        self.loginBtn.setObjectName("loginBtn")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(110, 50, 511, 301))
        self.label.setStyleSheet("border: none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../JarvisImages/loginFailed.gif"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.NewUserBtn = QtWidgets.QPushButton(self.frame)
        self.NewUserBtn.setGeometry(QtCore.QRect(390, 390, 171, 61))
        self.NewUserBtn.setStyleSheet("border-image: url(:/JarvisImages/newUser.png);")
        self.NewUserBtn.setText("")
        self.NewUserBtn.setObjectName("NewUserBtn")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.userNameEntry.setPlaceholderText(_translate("Widget", "USERNAME"))
        self.passwordEntry.setPlaceholderText(_translate("Widget", "PASSWORD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
