# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1080, 720)
        Widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(290, 10, 531, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../JarvisImages/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(750, 100, 321, 511))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../JarvisImages/ironmanSidePose.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(59, 116, 631, 401))
        self.label_3.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.loginBtn = QtWidgets.QPushButton(Widget)
        self.loginBtn.setGeometry(QtCore.QRect(110, 570, 171, 61))
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn.setStyleSheet("border-image: url(:/JarvisImages/loginButton.png);")
        self.loginBtn.setText("")
        self.loginBtn.setObjectName("loginBtn")
        self.exitBtn = QtWidgets.QPushButton(Widget)
        self.exitBtn.setGeometry(QtCore.QRect(440, 570, 171, 61))
        self.exitBtn.setStyleSheet("border-image: url(:/JarvisImages/exitButton.png);")
        self.exitBtn.setText("")
        self.exitBtn.setObjectName("exitBtn")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
